import = [
  "~/.config/alacritty/themes/mocha.toml"
  # "~/.config/alacritty/themes/coolnight.toml"
  # "~/.config/alacritty/themes/dracula.toml"
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

# [shell]
# program = "bash"
# program = "/usr/bin/zsh"

# shell = "C:\\Windows\\System32\\bash.exe"

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
# decorations = "Buttonless"  # (macOS only)
startup_mode = "Maximized"
dynamic_padding = true
padding = { x = 0, y = 0 }
class = {instance= "Alacritty",general="Alacritty"}
opacity = 0.8
blur = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[font]
normal = { family = "JetBrains Mono", style = "Medium" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "MediumItalic" }
bold_italic = { family = "JetBrains Mono", style = "BoldItalic" }
builtin_box_drawing = true
size=12

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 300
unfocused_hollow = true
thickness = 0.15


[colors]
draw_bold_text_with_bright_colors = true
